# Generated by Suyog Sakegaonkar and VTR
# DO NOT EDIT THIS FILE DIRECTLY
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{selenium-framework}
  s.version = '1.0.5'
  s.date = %q{2013-05-03}
  s.default_executable = %q{testframe}
  s.summary = %q{This gem is used for selenium automation framework}
  s.description = %q{This gem is used for selenium automation framework}
  s.authors = ['Suyog Sakegaonkar, Thiyagarajan Veluchamy']
  s.email = 'suyogsakegaonkar@gmail.com, thiyagarajannv@gmail.com'
  s.files = ['lib/userextension/user_extension.rb', 'lib/selenium-framework.rb', 'lib/modules/login/login.rb', 'bin/copyfiles/Gemfile', 'bin/copyfiles/selenium-framework.yml', 'bin/copyfiles/include.rb', 'bin/copyfiles/project_file.rb', 'lib/userextension/pre_requisite.rb','lib/userextension/utilities.rb']
  s.require_path = 'lib'
  s.executables << 'testframe'
  s.post_install_message = 'Successfully get installed'
  s.description = 'Selenium Automation FrameWork'
  s.homepage = 'https://github.com/webonise/AutomationFramework'
  s.extra_rdoc_files = ['LICENSE', 'README.md']
  s.add_dependency(%q<bundler>)
  s.add_dependency(%q<selenium-webdriver>)
  s.add_dependency(%q<mail>)
  s.add_dependency(%q<faker>)
  s.add_dependency(%q<nokogiri>)
  s.add_dependency(%q<selenium-client>)
  s.add_dependency(%q<pry>)
end
